### ISSUE TITLE
Can't initialize the database...

### ISSUE THREAD

**Issue by victornoel** [waarp/WaarpR66#153]
Hi,

I'm playing with Waarp and I can't even initialize the database, I suspect there is a bug somewhere…

When I run r66init bin/Linux/conf/config-server.xml -initdb (I updated the content of the xml file of course), I get this error:
```
26/05/2015/14:57:30.876 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.initialize(DbSession.java:168) : Cannot create Connection
26/05/2015/14:57:30.878 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.error(DbSession.java:341) : SQLException: Database "/home/vnoel/Linagora/Veilles/Waarp/AllJarsWaarpR66-3.0.2/data/openr66" not found [90013-176] SQLState: 90013VendorError: 90013
26/05/2015/14:57:30.881 WARN [org.waarp.common.database.DbAdmin] [main] org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:178) : Attempt of connection in error: 0
org.waarp.common.database.exception.WaarpDatabaseNoConnectionException: Cannot create Connection
	at org.waarp.common.database.DbSession.initialize(DbSession.java:177) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbSession.<init>(DbSession.java:201) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:175) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.openr66.database.model.DbModelFactory.initialize(DbModelFactory.java:66) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1730) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2009) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:119) [WaarpR66-3.0.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database "/home/vnoel/Linagora/Veilles/Waarp/AllJarsWaarpR66-3.0.2/data/openr66" not found [90013-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.openSession(Engine.java:55) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.openSession(Engine.java:164) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSession(Engine.java:125) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSession(Engine.java:27) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.Driver.connect(Driver.java:74) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:354) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:386) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:228) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:200) ~[h2-1.3.176.jar:1.3.176]
	at org.waarp.common.database.model.DbModelH2.getDbConnection(DbModelH2.java:126) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbSession.initialize(DbSession.java:156) ~[WaarpCommon-3.0.2.jar:na]
	... 6 common frames omitted
26/05/2015/14:57:30.883 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.initialize(DbSession.java:168) : Cannot create Connection
26/05/2015/14:57:30.883 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.error(DbSession.java:341) : SQLException: Database "/home/vnoel/Linagora/Veilles/Waarp/AllJarsWaarpR66-3.0.2/data/openr66" not found [90013-176] SQLState: 90013VendorError: 90013
26/05/2015/14:57:30.883 WARN [org.waarp.common.database.DbAdmin] [main] org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:178) : Attempt of connection in error: 1
org.waarp.common.database.exception.WaarpDatabaseNoConnectionException: Cannot create Connection
	at org.waarp.common.database.DbSession.initialize(DbSession.java:177) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbSession.<init>(DbSession.java:201) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:175) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.openr66.database.model.DbModelFactory.initialize(DbModelFactory.java:66) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1730) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2009) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:119) [WaarpR66-3.0.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database "/home/vnoel/Linagora/Veilles/Waarp/AllJarsWaarpR66-3.0.2/data/openr66" not found [90013-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.openSession(Engine.java:55) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.openSession(Engine.java:164) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSession(Engine.java:125) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSession(Engine.java:27) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.Driver.connect(Driver.java:74) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:354) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:386) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:228) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:200) ~[h2-1.3.176.jar:1.3.176]
	at org.waarp.common.database.model.DbModelH2.getDbConnection(DbModelH2.java:126) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbSession.initialize(DbSession.java:156) ~[WaarpCommon-3.0.2.jar:na]
	... 6 common frames omitted
26/05/2015/14:57:30.884 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.initialize(DbSession.java:168) : Cannot create Connection
26/05/2015/14:57:30.884 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.error(DbSession.java:341) : SQLException: Database "/home/vnoel/Linagora/Veilles/Waarp/AllJarsWaarpR66-3.0.2/data/openr66" not found [90013-176] SQLState: 90013VendorError: 90013
26/05/2015/14:57:30.885 WARN [org.waarp.common.database.DbAdmin] [main] org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:178) : Attempt of connection in error: 2
org.waarp.common.database.exception.WaarpDatabaseNoConnectionException: Cannot create Connection
	at org.waarp.common.database.DbSession.initialize(DbSession.java:177) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbSession.<init>(DbSession.java:201) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:175) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.openr66.database.model.DbModelFactory.initialize(DbModelFactory.java:66) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1730) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2009) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:119) [WaarpR66-3.0.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database "/home/vnoel/Linagora/Veilles/Waarp/AllJarsWaarpR66-3.0.2/data/openr66" not found [90013-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.openSession(Engine.java:55) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.openSession(Engine.java:164) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSession(Engine.java:125) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Engine.createSession(Engine.java:27) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.Driver.connect(Driver.java:74) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:354) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:386) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:228) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:200) ~[h2-1.3.176.jar:1.3.176]
	at org.waarp.common.database.model.DbModelH2.getDbConnection(DbModelH2.java:126) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.common.database.DbSession.initialize(DbSession.java:156) ~[WaarpCommon-3.0.2.jar:na]
	... 6 common frames omitted
26/05/2015/14:57:30.885 ERROR [org.waarp.common.database.DbAdmin] [main] org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:207) : Cannot connect to Database!
26/05/2015/14:57:30.885 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1756) : Unable to Connect to DB
org.waarp.common.database.exception.WaarpDatabaseNoConnectionException: Cannot connect to database
	at org.waarp.common.database.DbAdmin.<init>(DbAdmin.java:208) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.openr66.database.model.DbModelFactory.initialize(DbModelFactory.java:66) ~[WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1730) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2009) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:119) [WaarpR66-3.0.2.jar:na]
26/05/2015/14:57:30.885 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2010) : Cannot load Database configuration
26/05/2015/14:57:30.886 ERROR [org.waarp.openr66.server.ServerInitDatabase] [main] org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:121) : Needs a correct configuration file as first argument
```

So I thought it was because of the IFEXISTS=TRUE parameter for the H2 database but if I then remove it, I get the following error:
```
26/05/2015/14:57:42.533 ERROR [org.waarp.common.database.DbRequest] [main] org.waarp.common.database.DbRequest.select(DbRequest.java:124) : SQL Exception Request:SELECT * FROM  CONFIGURATION  Table "CONFIGURATION" not found; SQL statement:
SELECT * FROM  CONFIGURATION  [42102-176]
26/05/2015/14:57:42.535 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.error(DbSession.java:341) : SQLException: Table "CONFIGURATION" not found; SQL statement:
SELECT * FROM  CONFIGURATION  [42102-176] SQLState: 42S02VendorError: 42102
26/05/2015/14:57:42.537 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1766) : Database is not yet initiated: run ServerInitDatabase -initdb first
org.waarp.common.database.exception.WaarpDatabaseSqlException: SQL Exception Request:SELECT * FROM  CONFIGURATION 
	at org.waarp.common.database.DbRequest.select(DbRequest.java:128) ~[WaarpCommon-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1764) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2009) [WaarpR66-3.0.2.jar:na]
	at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:119) [WaarpR66-3.0.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Table "CONFIGURATION" not found; SQL statement:
SELECT * FROM  CONFIGURATION  [42102-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.readTableOrView(Parser.java:5213) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.readTableFilter(Parser.java:1220) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1859) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1968) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1853) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1674) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parseSelect(Parser.java:1662) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parsePrepared(Parser.java:434) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parse(Parser.java:306) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.parse(Parser.java:278) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.command.Parser.prepareCommand(Parser.java:243) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Session.prepareLocal(Session.java:442) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.engine.Session.prepareCommand(Session.java:384) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172) ~[h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160) ~[h2-1.3.176.jar:1.3.176]
	at org.waarp.common.database.DbRequest.select(DbRequest.java:120) ~[WaarpCommon-3.0.2.jar:na]
	... 3 common frames omitted
26/05/2015/14:57:42.538 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.loadDirectory(FileBasedConfiguration.java:1056) : This is not a directory from Config file: Home
26/05/2015/14:57:42.538 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationInitDatabase(FileBasedConfiguration.java:2014) : Cannot load Directory configuration
26/05/2015/14:57:42.538 ERROR [org.waarp.openr66.server.ServerInitDatabase] [main] org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:121) : Needs a correct configuration file as first argument
```

Obviously there is something wrong with the initialisation code :)

Thanks!

**Comment by fredericBregier** [comment]
Not necesseraly ;-)
You have to launch the ServerInitDatabase as following: (supposely you're using Linux ENV_R66 correctly configured)
`r66init -initdb -dir /yourpath/conf/ -auth /yourpath/authent.xml`

- In the lib path, you must have (preferably) one and only one JDBC driver (here I suppose H2)
- `-initdb` is mandatory in the command line

For specific option of H2 database (as `IFEXISTS=TRUE`), I suggest to go to the H2 Database web site directly. Indeed, this option specifies that the database must exist, and if not the connection is in error. This is recommended once the database is created in order to prevent wrong side effect after (creation of newly empty database).

Here the error you got means the database is created but empty (no table created).

**Comment by fredericBregier** [comment]
If your database was wrongly created previously, could you try to remove it and recreate it through `-initdb`option ?
I retry on my side and I've got no issue...

**Comment by victornoel** [comment]
Hi, I didn't know that I should have used this syntax.

It's not clear what is /yourpath/conf/ in this scenario… I have all my settings (I think) in bin/Linux/conf/config-server.xml.
I forgot to say I was using version 3.0.2 also.
I updated the OpenR66-authent-A.xml file with information for the host I'm creating (hosta in the example given), but I'm not really sure to understand why I need authentication information to initialise the database :)

And I still get the error (trying to access the database not even created…) with the following command: ```r66init -initdb -dir bin/Linux/conf/ config/OpenR66-authent-A.xml```

**Comment by victornoel** [comment]
Apparently it works with 3.0.3… (just using initDb). Well actually what happens is that the error appears, but then the database is correctly initialised… and I now understand why you need the auth file: so that the database is filled with it…

Now I can't login in the web ui: I use the login/pass filled in config-serverA-minimal.xml (which is the server config I am now using, updated with the correct paths), but it tells me the user does not exist in the database…

**Comment by fredericBregier** [comment]
@victornoel The detail of the command lines are explained here: 
http://waarp.github.io/Waarp/WaarpR66CommandLine.html
and in general form (Java form) here:
http://waarp.github.io/Waarp/WaarpR66Command.html
Moreover, installation process is described here:
http://waarp.github.io/Waarp/WaarpR66Configuration.html

Your current issue seems related to:
http://waarp.github.io/Waarp/WaarpR66Configuration.html#PWD
and how to fill it in the XML configuration file:
http://waarp.github.io/Waarp/WaarpR66Configuration.html#SSL

I hope you find what you need on the web site. ;-)

**Comment by victornoel** [comment]
Yes, I saw all of that :) Thanks for the help!

**Comment by fredericBregier** [comment]
I hope you find your way ;-)
If not, please open a new issue for the specific problem.
I closed this one since you finally managed to setup the database...

**Comment by victornoel** [comment]
Yep, perfect, thanks (and I solved my need for the admin password :)
