### ISSUE TITLE
Exception AdminGui on Linux

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#172]
Hi,

Following online manuals, I have installed WaarpR66 on Linux Centos6 .he GUI starts correctly using
`$JAVARUNCLIENT org.waarp.administrator.AdminGui conf/config-serverA.xml`. The problem is Edit XML, when I click on that button application generates this error output. It seems looking for some graphical content that is not available.

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.fg.util.FadingFilter.fade(FadingFilter.java:73)
	at org.waarp.xample.FHistoryButton.<init>(FHistoryButton.java:96)
	at org.waarp.xample.XAmple.<init>(XAmple.java:184)
	at org.waarp.xample.AdminXample.<init>(AdminXample.java:51)
	at org.waarp.xample.AdminXample.start(AdminXample.java:117)
	at org.waarp.administrator.AdminGui$2.actionPerformed(AdminGui.java:209)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)`

**Comment by fredericBregier** [comment]
Hi,
After cheking, it seems we have an issue on the Jar building procedure for WaarpXmlEditor. It misses the gif to be included, which causes your null exception.
I upload in this issue a quick fix with the correct jar. Could you give it a try (replacing the previous jar with this one) ?

[WaarpXmlEditor-1.0.1.jar.zip](https://github.com/waarp/WaarpR66/files/81823/WaarpXmlEditor-1.0.1.jar.zip)

**Comment by fredericBregier** [comment]
[WaarpXmlEditor-1.0.1.jar.zip](https://github.com/waarp/WaarpR66/files/81835/WaarpXmlEditor-1.0.1.jar.zip)
Or better this one (generated through maven this time)

**Comment by alexbarta** [comment]
Hi,
Last jar works fine!

Thanks for your fast reply & keep up the good work .

Alex

**Comment by fredericBregier** [comment]
OK thanks for reporting !
We will update later on this jar in the next release.
