### ISSUE TITLE
Blowfish crypted password wrong key size client exception

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#200]
Hi Frédéric,

I'm testing blowfish keys instead of less secure DES keys . 
After running this creation command for blowfish key:
```
/opt/R66/bin/r66command.sh org.waarp.uip.WaarpPassword -ko ./test.blf -blf -pwd password -po test-passwd.ggp
Start R66Command
CryptedPwd: 17bfd78c2c2012609d88148dbefd8358
R66Command stopped

```

and consequently configuring the client with new blf key and crypted pwd, I'm currently running into a wrong keysize exception. Actually blf key in bytes is smaller than test des key

```
-rw-r--r--  1 waarp mft 7 Jun 24 10:04 certs/test-key.blf
-rw-r--r--. 1 waarp mft 8 May 31 12:29 certs/test-key.des

```
Here the exception:
```
24/06/2016/10:19:23.625 WARN [org.waarp.common.crypto.KeyObject] [main] org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:315) : Decrypt Error
java.security.InvalidKeyException: Wrong key size
        at com.sun.crypto.provider.DESCrypt.init(DESCrypt.java:536) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.ElectronicCodeBook.init(ElectronicCodeBook.java:93) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.CipherCore.init(CipherCore.java:582) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.CipherCore.init(CipherCore.java:458) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.DESCipher.engineInit(DESCipher.java:186) ~[sunjce_provider.jar:1.8.0_91]
        at javax.crypto.Cipher.implInit(Cipher.java:802) ~[na:1.8.0_91]
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[na:1.8.0_91]
        at javax.crypto.Cipher.init(Cipher.java:1249) ~[na:1.8.0_91]
        at javax.crypto.Cipher.init(Cipher.java:1186) ~[na:1.8.0_91]
        at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:312) [WaarpCommon-3.0.6.jar:na]
        at org.waarp.common.crypto.KeyObject.decryptHexInBytes(KeyObject.java:341) [WaarpCommon-3.0.6.jar:na]
        at org.waarp.common.crypto.KeyObject.decryptHexFile(KeyObject.java:390) [WaarpCommon-3.0.6.jar:na]
        at org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:215) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.configuration.FileBasedConfiguration.loadAuthentication(FileBasedConfiguration.java:802) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.configuration.FileBasedConfiguration.setClientConfigurationFromXml(FileBasedConfiguration.java:2461) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.client.AbstractTransfer.getParams(AbstractTransfer.java:236) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.client.MultipleDirectTransfer.main(MultipleDirectTransfer.java:278) [WaarpR66-3.0.6.jar:na]
24/06/2016/10:19:23.628 ERROR [org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration] [main] org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:217) : Cannot read key for hostId clientwaarp-1
java.security.InvalidKeyException: Wrong key size
        at com.sun.crypto.provider.DESCrypt.init(DESCrypt.java:536) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.ElectronicCodeBook.init(ElectronicCodeBook.java:93) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.CipherCore.init(CipherCore.java:582) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.CipherCore.init(CipherCore.java:458) ~[sunjce_provider.jar:1.8.0_91]
        at com.sun.crypto.provider.DESCipher.engineInit(DESCipher.java:186) ~[sunjce_provider.jar:1.8.0_91]
        at javax.crypto.Cipher.implInit(Cipher.java:802) ~[na:1.8.0_91]
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[na:1.8.0_91]
        at javax.crypto.Cipher.init(Cipher.java:1249) ~[na:1.8.0_91]
        at javax.crypto.Cipher.init(Cipher.java:1186) ~[na:1.8.0_91]
        at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:312) ~[WaarpCommon-3.0.6.jar:na]
        at org.waarp.common.crypto.KeyObject.decryptHexInBytes(KeyObject.java:341) ~[WaarpCommon-3.0.6.jar:na]
        at org.waarp.common.crypto.KeyObject.decryptHexFile(KeyObject.java:390) ~[WaarpCommon-3.0.6.jar:na]
        at org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:215) ~[WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.configuration.FileBasedConfiguration.loadAuthentication(FileBasedConfiguration.java:802) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.configuration.FileBasedConfiguration.setClientConfigurationFromXml(FileBasedConfiguration.java:2461) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.client.AbstractTransfer.getParams(AbstractTransfer.java:236) [WaarpR66-3.0.6.jar:na]
        at org.waarp.openr66.client.MultipleDirectTransfer.main(MultipleDirectTransfer.java:278) [WaarpR66-3.0.6.jar:na]

```
Best Regards 

Alex

**Comment by fredericBregier** [comment]
@alexbarta Effectively, the code currently use only Des format (as seen in the log).
We might add the possibility to change to other formats.
@bcarlin FYI

**Comment by bcarlin** [comment]
It might be interesting to add support for other encryption algorithms (3DES, Blowfish, AES, etc...).
We accept pull requests for that.
