### ISSUE TITLE
Rest API - Internal Server Error when "getAll"

### ISSUE THREAD

**Issue by type0lang** [waarp/WaarpR66#203]
When invoking simple endpoint like `curl -XGET http://[mydns]:8068/hosts/` or `curl -XGET http://[mydns]:8068/rules/`
an internal server error response is returned
```
{
  "X-method": "GET",
  "path": "/hosts/",
  "base": "hosts",
  "uri": {},
  "answer": {
    "filter": {}
  },
  "message": "Internal Server Error",
  "code": 500
}
```
and a NPE is raised:
```
17/11/2016/08:42:36.673 DEBUG [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-5] org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:386) : Msg Received
17/11/2016/08:42:36.673 DEBUG [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-5] org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:395) : DEBUG: {"hasBody":false,"X-method":"GET","path":"/hosts/","base":"hosts","uri":{},"header":{"Host":"10.147.144.67:443","Connection":"keep-alive","Postman-Token":"5d673d3b-034b-d377-9540-8e89dd95268d","Cache-Control":"no-cache","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","Content-Type":"application/json","Accept":"*/*","Accept-Encoding":"gzip, deflate, sdch","Accept-Language":"en-US,en;q=0.8,it;q=0.6"}}
17/11/2016/08:42:36.673 DEBUG [org.waarp.openr66.protocol.http.rest.HttpRestR66Handler] [HttpWorker-5] org.waarp.openr66.protocol.http.rest.HttpRestR66Handler.checkConnection(HttpRestR66Handler.java:260) : Request: {"hasBody":false,"X-method":"GET","path":"/hosts/","base":"hosts","uri":{},"header":{"Host":"10.147.144.67:443","Connection":"keep-alive","Postman-Token":"5d673d3b-034b-d377-9540-8e89dd95268d","Cache-Control":"no-cache","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","Content-Type":"application/json","Accept":"*/*","Accept-Encoding":"gzip, deflate, sdch","Accept-Language":"en-US,en;q=0.8,it;q=0.6"}} ### {}
17/11/2016/08:42:36.675 DEBUG [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-5] org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:386) : Msg Received
17/11/2016/08:42:36.675 DEBUG [org.waarp.gateway.kernel.rest.RestArgument] [HttpWorker-5] org.waarp.gateway.kernel.rest.RestArgument.setFromArgument(RestArgument.java:338) : DEBUG: {"X-method":"GET","path":"/hosts/","base":"hosts","uri":{}}
 {"hasBody":false,"X-method":"GET","path":"/hosts/","base":"hosts","uri":{},"header":{"Host":"10.147.144.67:443","Connection":"keep-alive","Postman-Token":"5d673d3b-034b-d377-9540-8e89dd95268d","Cache-Control":"no-cache","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","Content-Type":"application/json","Accept":"*/*","Accept-Encoding":"gzip, deflate, sdch","Accept-Language":"en-US,en;q=0.8,it;q=0.6"},"X-Auth-Role":127}
17/11/2016/08:42:36.677 WARN [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-5] org.waarp.gateway.kernel.rest.HttpRestHandler.exceptionCaught(HttpRestHandler.java:751) : Exception Received
java.lang.NullPointerException: null
        at com.fasterxml.jackson.databind.node.ObjectNode.setAll(ObjectNode.java:376) ~[jackson-databind-2.6.2.jar:2.6.2]
        at org.waarp.gateway.kernel.rest.RestArgument.addFilter(RestArgument.java:668) ~[WaarpGatewayKernel-3.0.4.jar:na]
        at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.getAll(DataModelRestMethodHandler.java:261) ~[WaarpGatewayKernel-3.0.4.jar:na]
        at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.endParsingRequest(DataModelRestMethodHandler.java:157) ~[WaarpGatewayKernel-3.0.4.jar:na]
        at org.waarp.gateway.kernel.rest.HttpRestHandler.bodyChunk(HttpRestHandler.java:692) ~[WaarpGatewayKernel-3.0.4.jar:na]
        at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:427) ~[WaarpGatewayKernel-3.0.4.jar:na]
        at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:87) ~[WaarpGatewayKernel-3.0.4.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
17/11/2016/08:42:36.678 DEBUG [org.waarp.gateway.kernel.rest.DataModelRestMethodHandler] [HttpWorker-5] org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.sendResponse(DataModelRestMethodHandler.java:400) : Will write: null

17/11/2016/08:42:36.679 DEBUG [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-5] org.waarp.gateway.kernel.rest.HttpRestHandler.finalizeSend(HttpRestHandler.java:708) : Cleaned
```

**Comment by bcarlin** [comment]
Those request needs a body to work.
While we fix that, you can just send an empty json object as the body. Default filters will be applied:

~~~
$ curl -XGET http://127.0.1.1:8088/hosts --data '{}'
{"X-method":"GET","path":"/hosts","base":"hosts","uri":{},"answer":{"filter":{},"count":0,"limit":100},"command":"MULTIGET","message":"OK","code":200}
~~~

Note: for the endpoint `/hosts`, the default for the `ISACTIVE` filter is `false`, so anyway, a better base query would be 

~~~
$ curl -XGET http://127.0.1.1:8088/hosts --data '{"ISACTIVE":true}'
{"X-method":"GET","path":"/hosts","base":"hosts","uri":{},"answer":{"filter":{"ISACTIVE":true},"results":[{"@model":"DbHostAuth","ADDRESS":"127.0.0.1","PORT":6666,"ISSSL":false,"HOSTKEY":"NWE0YjdjNmE2NjA2NWNiYjYyMmFjZWZlYzhjM2EzMDI=","ADMINROLE":false,"ISCLIENT":false,"ISACTIVE":true,"ISPROXIFIED":false,"UPDATEDINFO":0,"HOSTID":"server1"}],"count":1,"limit":100},"command":"MULTIGET","message":"OK","code":200}
~~~
