### ISSUE TITLE
Setup bi-directionnal transfer between 2 R66 instances

### ISSUE THREAD

**Issue by fjudith** [waarp/WaarpR66#204]
I'm trying to setup bi-directionnal transfer with two r66 instances to simulate exchange with a tier organization.
Therefore each instance is running on its own key.

Could you provide guidelines to setup such typical scenario ?

I'm getting the following error when attempting to import key from server1 to server2.

```
[root@42e5d61f1bf4 waarp]# r66init -auth /etc/waarp/conf.d/server1/server2_Authentication.xml
05:19:58.497 [main] DEBUG org.waarp.common.logging.WaarpLoggerFactory - org.waarp.common.logging.WaarpLoggerFactory.<clinit>(WaarpLoggerFactory.java:45) : Using Logback (SLF4J) as the default logging framework
05:19:58.506 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
05:19:58.542 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
05:19:58.555 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
05:19:58.579 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
05:19:58.585 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
05:19:58.587 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
05:19:58.589 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
05:19:58.592 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
05:19:58.600 [main] DEBUG io.netty.util.internal.PlatformDependent - Java version: 8
05:19:58.601 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
05:19:58.601 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
05:19:58.602 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
05:19:58.887 [main] DEBUG io.netty.util.internal.PlatformDependent - Javassist: available
05:19:58.888 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
05:19:58.889 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
05:19:58.889 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
05:19:58.890 [main] DEBUG io.netty.util.internal.PlatformDependent - io.netty.maxDirectMemory: 764280832 bytes
05:19:58.912 [main] INFO org.waarp.openr66.protocol.configuration.Configuration - org.waarp.openr66.protocol.configuration.Configuration.computeNbThreads(Configuration.java:1093) : Change default number of threads to 3
05:19:59.722 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.initialize(DbSession.java:116) : Open Db Conn: AMbO3EADCMf4Z_bczwABWIVTnuY=
05:19:59.741 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.useConnection(DbSession.java:270) : ThreadUsing: 1
05:19:59.744 [main] INFO org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1834) : Database connection: Admin:true NoCommitAdmin:true
05:19:59.745 [main] INFO org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1838) : DefaultTransactionIsolation: 2 MaxConnections: 8192 MaxStatements: 0
05:19:59.772 [main] DEBUG org.waarp.openr66.protocol.configuration.PartnerConfiguration - org.waarp.openr66.protocol.configuration.PartnerConfiguration.isVersion2GEQVersion1(PartnerConfiguration.java:291) : 1: 2:4:25 <=? 2:4:13 = false
05:19:59.773 [main] DEBUG org.waarp.openr66.protocol.configuration.PartnerConfiguration - org.waarp.openr66.protocol.configuration.PartnerConfiguration.isVersion2GEQVersion1(PartnerConfiguration.java:291) : 1: 2:4:25 <=? 2:4:17 = false
05:19:59.774 [main] DEBUG org.waarp.openr66.protocol.configuration.PartnerConfiguration - org.waarp.openr66.protocol.configuration.PartnerConfiguration.isVersion2GEQVersion1(PartnerConfiguration.java:291) : 1: 2:4:25 <=? 2:4:23 = false
05:19:59.774 [main] DEBUG org.waarp.openr66.protocol.configuration.PartnerConfiguration - org.waarp.openr66.protocol.configuration.PartnerConfiguration.isVersion2GTVersion1(PartnerConfiguration.java:334) : 1: 2:4:25 <? 2:4:25 = false
05:19:59.775 [main] DEBUG org.waarp.openr66.server.ServerInitDatabase - org.waarp.openr66.server.ServerInitDatabase.upgradedb(ServerInitDatabase.java:292) : Database schema is up to date
05:19:59.779 [main] INFO org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:1223) : Limit of Runner: 10000
05:19:59.780 [main] INFO org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:1231) : Delay Commander: 5000
05:19:59.781 [main] INFO org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:1240) : Delay Retry: 10000
05:19:59.781 [main] DEBUG org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:1334) : No setup of ContraintLimitHandler
05:19:59.782 [main] INFO org.waarp.openr66.configuration.FileBasedConfiguration - org.waarp.openr66.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:1368) : DigestAlgo used: MD5
05:19:59.845 [main] WARN org.waarp.common.crypto.KeyObject - org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:315) : Decrypt Error
javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:975)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:833)
        at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:313)
        at org.waarp.common.crypto.KeyObject.decryptHexInBytes(KeyObject.java:341)
        at org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:197)
        at org.waarp.openr66.server.ServerInitDatabase.loadHostAuth(ServerInitDatabase.java:312)
        at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:157)
05:19:59.853 [main] ERROR org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration - org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:199) : Cannot read key for hostId server2:3bfb99bf1efc88bd8a26e5285e7cbe82547c7ff3f63dfe65
05:19:59.854 [main] WARN org.waarp.common.crypto.KeyObject - org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:315) : Decrypt Error
javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:975)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:833)
        at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:313)
        at org.waarp.common.crypto.KeyObject.decryptHexInBytes(KeyObject.java:341)
        at org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:197)
        at org.waarp.openr66.server.ServerInitDatabase.loadHostAuth(ServerInitDatabase.java:312)
        at org.waarp.openr66.server.ServerInitDatabase.main(ServerInitDatabase.java:157)
05:19:59.861 [main] ERROR org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration - org.waarp.openr66.configuration.AuthenticationFileBasedConfiguration.loadAuthentication(AuthenticationFileBasedConfiguration.java:199) : Cannot read key for hostId server2-ssl:3bfb99bf1efc88bd8a26e5285e7cbe82547c7ff3f63dfe65
Load done
05:19:59.863 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.endUseConnection(DbSession.java:278) : ThreadUsing: 0
05:19:59.864 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:375) : Closing internal db connection: 0
05:19:59.966 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:386) : DbConnection still in use: 0
05:19:59.970 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:397) : Close Db Conn: AMbO3EADCMf4Z_bczwABWIVTnuY=
05:19:59.979 [main] INFO org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:409) : Current cached connection: -1
05:19:59.983 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:337) : Closing internal db connection
05:19:59.986 [main] DEBUG org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:341) : Connection already closed
```

**Comment by bcarlin** [comment]
I reckon there are two possibilities:

- the password was not encrypted with DES (while Waarp password tool can encrypt passwords using blowfish, Waarp R66 only supports DES)
- the password was not encrypted using the same DES key used to encrypt it (DES is symmetric)

**Comment by bcarlin** [comment]
Is it still an issue ?
