### ISSUE TITLE
r66command.sh does not report   error if jdbc driver is not in classpath  (server.sh does)

### ISSUE THREAD

**Issue by MichaelReicheOracle** [waarp/WaarpR66#206]
r66command.sh does not report   error if jdbc driver is not in classpath.  (server.sh does).

[mreiche@den00tuy ~/waarp]$ r66command.sh org.waarp.openr66.server.ServerInitDatabase config/config-serverA.xml -initDb
Start R66Command
R66Command stopped
[mreiche@den00tuy ~/waarp]$ 
[mreiche@den00tuy ~/waarp]$ cat log/R66Client.log 
[mreiche@den00tuy ~/waarp]$ 

[mreiche@den00tuy ~/waarp]$ vi  bin/Linux/bin/r66command.sh bin/Linux/bin/server.sh
2 files to edit
[mreiche@den00tuy ~/waarp]$ server.sh  config/config-serverA.xml 
Start R66Server
R66HOME=/scratch/mreiche/waarp
nohup: appending output to `nohup.out'

^Z
Suspended
[mreiche@den00tuy ~/waarp]$ bg
[1]    server.sh config/config-serverA.xml &
[mreiche@den00tuy ~/waarp]$ 
[mreiche@den00tuy ~/waarp]$ cat nohup.out 
02/12/2016/17:04:30.035 WARN [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.loadIdentity(FileBasedConfiguration.java:778) : Unable to find Host SSL ID in Config file so no SSL support will be used
02/12/2016/17:04:30.159 WARN [org.waarp.common.database.model.DbModelOracle] [main] org.waarp.common.database.model.DbModelOracle.<init>(DbModelOracle.java:116) : Some info: MaxConn: 0 LogTimeout: 30 ForceClose: 300000
02/12/2016/17:04:31.114 WARN [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.loadServerParam(FileBasedConfiguration.java:1046) : Multiple Monitor configuration unactive
02/12/2016/17:04:31.317 ERROR [org.waarp.common.database.DbPreparedStatement] [main] org.waarp.common.database.DbPreparedStatement.executeQuery(DbPreparedStatement.java:282) : SQL Exception executeQuery:SELECT count(*) FROM  HOSTS  WHERE ISPROXIFIED = true ORA-00904: "TRUE": invalid identifier

02/12/2016/17:04:31.318 ERROR [org.waarp.common.database.DbSession] [main] org.waarp.common.database.DbSession.error(DbSession.java:251) : SQLException: ORA-00904: "TRUE": invalid identifier
 SQLState: 42000VendorError: 904
02/12/2016/17:04:31.456 WARN [org.waarp.openr66.protocol.configuration.Configuration] [main] org.waarp.openr66.protocol.configuration.Configuration.pipelineInit(Configuration.java:662) : Server Thread: 8 Client Thread: 80 Runner Thread: 10000
02/12/2016/17:04:31.475 WARN [org.waarp.openr66.protocol.configuration.Configuration] [main] org.waarp.openr66.protocol.configuration.Configuration.r66Startup(Configuration.java:763) : SSL mode is desactivated
02/12/2016/17:04:31.512 WARN [org.waarp.openr66.protocol.networkhandler.NetworkTransaction] [main] org.waarp.openr66.protocol.networkhandler.NetworkTransaction.<init>(NetworkTransaction.java:155) : No SSL support configured
02/12/2016/17:04:32.033 WARN [org.waarp.openr66.server.R66Server] [main] org.waarp.openr66.server.R66Server.main(R66Server.java:55) : Server OpenR66 starts for hosta : Config: { ServerPort: 6666, ServerSslPort: 6667, ServerView: 8066, ServerAdmin: 8067, ThriftPort: 'NoThriftSupport', RestAddress: ['127.0.0.1:8068', 'All:8069'], TimeOut: 10000, BaseDir: '/scratch/mreiche/AllJarsWaarpR66-3.0.6', DigestAlgo: 'MD5', checkRemote: false, checkClient: false, snmpActive: true, chrootChecked: true, blacklist: true, isHostProxified: false}
Server OpenR66 starts for hosta
05/12/2016/11:49:44.356 WARN [org.waarp.openr66.protocol.localhandler.LocalTransaction] [WaarpShutdownHook] org.waarp.openr66.protocol.localhandler.LocalTransaction.shutdownLocalChannels(LocalTransaction.java:404) : Will inform LocalChannels of Shutdown: 0
05/12/2016/11:49:44.381 WARN [org.waarp.openr66.protocol.utils.ChannelUtils] [WaarpShutdownHook] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:387) : Exit: Give a delay of 10000 ms
05/12/2016/12:20:27.596 ERROR [org.waarp.openr66.server.R66Server] [main] org.waarp.openr66.server.R66Server.main(R66Server.java:63) : Startup of server is in error
java.lang.NoClassDefFoundError: com/mysql/jdbc/Driver
	at org.waarp.common.database.model.DbModelMysql.<init>(DbModelMysql.java:120) ~[WaarpCommon-3.0.6.jar:na]
	at org.waarp.common.database.model.DbModelMysql.<init>(DbModelMysql.java:98) ~[WaarpCommon-3.0.6.jar:na]
	at org.waarp.openr66.database.model.DbModelMysql.<init>(DbModelMysql.java:58) ~[WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.database.model.DbModelFactory.initialize(DbModelFactory.java:59) ~[WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1822) ~[WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2337) ~[WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.server.R66Server.initialize(R66Server.java:72) ~[WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.server.R66Server.main(R66Server.java:54) ~[WaarpR66-3.0.6.jar:na]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_40-ea]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_40-ea]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_40-ea]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40-ea]
	... 8 common frames omitted

**Comment by fredericBregier** [comment]
In general, I would recommend to have only one of the JDBC driver in the lib directory, not all. If you planto use Oracle and not Mysql or PostgreSql, then keep only this one.
I know this not mandatory but recommanded.

**Comment by bcarlin** [comment]
There is, however a bug on that to be fixed: Even with no JDBC driver at all in the classpath, initdb remains silent when it should fail.
