### ISSUE TITLE
getting config-serverA.xml to work // Decrypt Error javax.crypto.IllegalBlockSizeException: Input length must be multiple of 8 when decrypting with padded cipher

### ISSUE THREAD

**Issue by MichaelReicheOracle** [waarp/WaarpR66#208]
I'm trying to use the   config-serverA.xml configuration.  After plugging my database into the config file, I add rows to the HOSTS db table as follows, but when I run "Check" from the AdminGui, I get the error below (Input length must be multiple of 8 when decrypting with padded cipher).  Am I setting HOSTS.HOSTKEY to the correct value?

AdminGui -> Edit Password shows

/scratch/mreiche/waarp/config/certs/test-key.des
testpassword
3e7b3cf58ddd8133895411c6a078870d

Note that the HOSTKEY clob is convert to a string in the 'insert'.  After inserting, I have to manually (with Squirrel) set it to the binary - (the bytes 3e  7b  3c  f5  58  dd  d8  13  38  95  41  1c  6a  78  87  0d)

insert into HOSTS
(ADDRESS, PORT, ISSSL,  HOSTKEY,  ADMINROLE, ISACTIVE, ISCLIENT, ISPROXIFIED, UPDATEDINFO, HOSTID) values (
'10.196.63.210', 6666, '0', '3e7b3cf558ddd8133895411c6a78870d', 'Y', 'Y', 'N', 'N', 0, 'hosta');

insert into HOSTS
(ADDRESS, PORT, ISSSL,  HOSTKEY,  ADMINROLE, ISACTIVE, ISCLIENT, ISPROXIFIED, UPDATEDINFO, HOSTID) values (
'10.196.63.210', 6667, '1', '3e7b3cf558ddd8133895411c6a78870d', '1', '1', '0', '0', 0, 'hostas');

mysql> select * from HOSTS;
+---------------+------+-------+----------------------------------+-----------+----------+----------+-------------+-------------+--------+
| ADDRESS       | PORT | ISSSL | HOSTKEY                          | ADMINROLE | ISCLIENT | ISACTIVE | ISPROXIFIED | UPDATEDINFO | HOSTID |
+---------------+------+-------+----------------------------------+-----------+----------+----------+-------------+-------------+--------+
| 10.196.63.210 | 6666 |     0 | 3e7b3cf558ddd8133895411c6a78870d |         1 |        0 |        1 |           0 |           0 | hosta  |
| 10.196.63.210 | 6667 |     1 | 3e7b3cf558ddd8133895411c6a78870d |         1 |        0 |        1 |           0 |           0 | hostas |
+---------------+------+-------+----------------------------------+-----------+----------+----------+-------------+-------------+--------+
2 rows in set (0.00 sec)

[mreiche@den00tuy ~/waarp]$ r66command.sh org.waarp.administrator.AdminGui config/config-serverA.xml -pi config/certs/test-passwd.ggp 
Start R66Command
05/12/2016/13:08:26.526 WARN [org.waarp.common.database.model.DbModelMysql] [main] org.waarp.common.database.model.DbModelMysql.<init>(DbModelMysql.java:105) : Some info: MaxConn: 0 LogTimeout: 30 ForceClose: 300000
05/12/2016/13:08:27.334 WARN [org.waarp.openr66.protocol.configuration.Configuration] [main] org.waarp.openr66.protocol.configuration.Configuration.pipelineInit(Configuration.java:662) : Server Thread: 8 Client Thread: 80 Runner Thread: 10000
Cannot create a password if no password GGP file is specified with pi or po options
05/12/2016/13:08:31.714 WARN [org.waarp.common.crypto.KeyObject] [AWT-EventQueue-0] org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:315) : Decrypt Error
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 8 when decrypting with padded cipher
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:913) ~[sunjce_provider.jar:1.8.0_20]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824) ~[sunjce_provider.jar:1.8.0_20]
	at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314) ~[sunjce_provider.jar:1.8.0_20]
	at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_20]
	at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:313) [WaarpCommon-3.0.6.jar:na]
	at org.waarp.common.crypto.KeyObject.decryptHexInBytes(KeyObject.java:354) [WaarpCommon-3.0.6.jar:na]
	at org.waarp.openr66.database.data.DbHostAuth.getHostkey(DbHostAuth.java:732) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.sendValidationConnection(NetworkTransaction.java:575) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.createConnection(NetworkTransaction.java:387) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.createConnectionWithRetry(NetworkTransaction.java:295) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.client.Message.run(Message.java:164) [WaarpR66-3.0.6.jar:na]
	at org.waarp.administrator.AdminGui$3.actionPerformed(AdminGui.java:234) [WaarpAdministrator-3.0.1.jar:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [na:1.8.0_40-ea]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346) [na:1.8.0_40-ea]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.8.0_40-ea]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.8.0_40-ea]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [na:1.8.0_40-ea]
	at java.awt.Component.processMouseEvent(Component.java:6525) [na:1.8.0_40-ea]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_40-ea]
	at java.awt.Component.processEvent(Component.java:6290) [na:1.8.0_40-ea]
	at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40-ea]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40-ea]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40-ea]
	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40-ea]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) [na:1.8.0_40-ea]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533) [na:1.8.0_40-ea]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) [na:1.8.0_40-ea]
	at java.awt.Container.dispatchEventImpl(Container.java:2278) [na:1.8.0_40-ea]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_40-ea]
	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40-ea]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) [na:1.8.0_40-ea]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40-ea]
	at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40-ea]
	at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40-ea]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40-ea]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40-ea]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_40-ea]
	at java.awt.EventQueue$4.run(EventQueue.java:724) [na:1.8.0_40-ea]
	at java.awt.EventQueue$4.run(EventQueue.java:722) [na:1.8.0_40-ea]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40-ea]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40-ea]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) [na:1.8.0_40-ea]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40-ea]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40-ea]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40-ea]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40-ea]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40-ea]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40-ea]
05/12/2016/13:08:41.794 WARN [org.waarp.common.crypto.KeyObject] [AWT-EventQueue-0] org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:315) : Decrypt Error
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 8 when decrypting with padded cipher
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:913) ~[sunjce_provider.jar:1.8.0_20]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824) ~[sunjce_provider.jar:1.8.0_20]
	at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314) ~[sunjce_provider.jar:1.8.0_20]
	at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_20]
	at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:313) [WaarpCommon-3.0.6.jar:na]

**Comment by MichaelReicheOracle** [comment]
Turns out I made a typo in the key in the database.  It should be 3e7b3cf58ddd8133895411c6a078870d

And the error was "Given final block not propertly padded" (below).   The " Input length must be multiple of 8 " was from an earlier mistake I made.

05/12/2016/15:59:27.208 WARN [org.waarp.common.crypto.KeyObject] [LocalWorker-24] org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:315) : Decrypt Error
javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:966) ~[sunjce_provider.jar:1.8.0_20]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824) ~[sunjce_provider.jar:1.8.0_20]
	at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314) ~[sunjce_provider.jar:1.8.0_20]
	at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_20]
	at org.waarp.common.crypto.KeyObject.decrypt(KeyObject.java:313) [WaarpCommon-3.0.6.jar:na]
	at org.waarp.common.crypto.KeyObject.decryptHexInBytes(KeyObject.java:354) [WaarpCommon-3.0.6.jar:na]
	at org.waarp.openr66.database.data.DbHostAuth.getHostkey(DbHostAuth.java:732) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.localhandler.packet.AuthentPacket.validate(AuthentPacket.java:202) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.localhandler.ConnectionActions.authent(ConnectionActions.java:485) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.localhandler.LocalServerHandler.channelRead0(LocalServerHandler.java:132) [WaarpR66-3.0.6.jar:na]
	at org.waarp.openr66.protocol.localhandler.LocalServerHandler.channelRead0(LocalServerHandler.java:86) [WaarpR66-3.0.6.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.0.CR1.jar:4.1.0.CR1]
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.CR1.jar:4.1.0.CR1]
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154) [netty-all-4.1.0.CR1.jar:4.1.0.CR1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:154) [netty-all-4.1.0.CR1.jar:4.1.0.CR1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.0.CR1.jar:4.1.0.CR1]
