### ISSUE TITLE
Problem w/mysql-connector-java-6.0.5.jar waarp 3.0.7

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#212]
It seems not to be compatible with old mysql setup:
``` 
<db>
        <dbdriver>mysql</dbdriver>
        <dbserver>jdbc:mysql://<ip>:3306/waarp</dbserver>
        <dbuser>waarp</dbuser>
        <dbpasswd>****</dbpasswd>
</db>
```
```
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
29/12/2016/17:34:33.748 ERROR [org.waarp.openr66.server.R66Server] [main] org.waarp.openr66.server.R66Server.main(R66Server.java:63) : Startup of server is in error
java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlConnectionPoolDataSource
        at org.waarp.common.database.model.DbModelMysql.<init>(DbModelMysql.java:99)
        at org.waarp.openr66.database.model.DbModelMysql.<init>(DbModelMysql.java:58)
        at org.waarp.openr66.database.model.DbModelFactory.initialize(DbModelFactory.java:59)
        at org.waarp.openr66.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:1822)
        at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2337)
        at org.waarp.openr66.server.R66Server.initialize(R66Server.java:72)
        at org.waarp.openr66.server.R66Server.main(R66Server.java:54)
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 common frames omitted
```
Any insight of which dbdriver should I use instead?

Regards

Alex

**Comment by fredericBregier** [comment]
The issue is due to version 6 of driver, which changes its class name, while staying with version 5 should work for now .
Note that version 5 works with last mysql server.

@bcarlin. We should add one option to allow to specify the real jdbc class name, since this could be an error with other drivers too (as version 6 of mysql driver or mariadb driver where the class name changed but not the api),  something to add optionally as <driverclassname>? Wdyt ?

**Comment by bcarlin** [comment]
:sweat: the switch to Mysql Connector/J 6.0 was too premature... It is not yet in general availability (only at a developer preview stage). As it is mentioned on https://dev.mysql.com/doc/connector-j/6.0/en/connector-j-versions.html , it is only compatible with Java 1.8 and drops support for MySQL 5.1 which is imo still widely used... I shouldn't have let this go...

A 3.0.8 version is already baking and is expected in February. I propose a rollback to Mysql Connector/J 5.1 in this version.
