### ISSUE TITLE
 REST API call Post /rules not working 

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#215]
Hi @fredericBregier, @bcarlin 

It seems I have found a strange bug when creating rules by POST on api endpoint. Compare the following commands.
**# working command**: I left unfilled  ```"SERRORTASKS": "<tasks></tasks>"```
```
curl -sS -XPOST -d '{"@model":"DbRule",HOSTIDS:null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS": "<tasks></tasks>","UPDATEDINFO":0,"IDRULE":"test"}' 'localhost:8088/rules' 
```
**# not working command**, all tasks are filled but returns ```{
  "X-method": "POST",
  "path": "/rules",
  "base": "rules",
  "uri": {},
  "message": "Bad Request",
  "code": 400,
  "detail": "Issue while inserting into database"
}```

```
curl -sS -XPOST -d '{"@model":"DbRule",HOSTIDS:null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","UPDATEDINFO":0,"IDRULE":"test_2"}' 'localhost:8088/rules'
```

Actually POST call works everytime I leave at least one the tasks empty. I found out this by running http rest tests contained in this project.

```
01:38:52.963 [main] DEBUG org.waarp.gateway.kernel.rest.client.HttpRestClientHelper - org.waarp.gateway.kernel.rest.client.HttpRestClientHelper.sendQuery(HttpRestClientHelper.java:174) : Prepare request: POST:rules:{"@model":"DbRule","HOSTIDS":"<hostids><hostid>hosta</hostid><hostid>hostZZ</hostid></hostids>","MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","UPDATEDINFO":0,"IDRULE":"test_send"}
01:38:52.963 [main] DEBUG org.waarp.gateway.kernel.rest.client.HttpRestClientHelper - org.waarp.gateway.kernel.rest.client.HttpRestClientHelper.sendQuery(HttpRestClientHelper.java:191) : Authent encoded
01:38:52.963 [main] DEBUG org.waarp.gateway.kernel.rest.client.HttpRestClientHelper - org.waarp.gateway.kernel.rest.client.HttpRestClientHelper.sendQuery(HttpRestClientHelper.java:205) : Uri ready: /rules
01:38:52.963 [main] DEBUG org.waarp.gateway.kernel.rest.client.HttpRestClientHelper - org.waarp.gateway.kernel.rest.client.HttpRestClientHelper.sendQuery(HttpRestClientHelper.java:209) : Add body
01:38:52.963 [main] DEBUG org.waarp.gateway.kernel.rest.client.HttpRestClientHelper - org.waarp.gateway.kernel.rest.client.HttpRestClientHelper.sendQuery(HttpRestClientHelper.java:225) : Send request
01:38:52.967 [Rest_/_-14] DEBUG org.waarp.openr66.protocol.http.rest.client.HttpRestR66ClientResponseHandler - org.waarp.openr66.protocol.http.rest.client.HttpRestR66ClientResponseHandler.channelRead0(HttpRestR66ClientResponseHandler.java:314) : referer: /rules STATUS: 400 Bad Request
01:38:52.968 [Rest_/_-14] ERROR org.waarp.openr66.protocol.http.rest.client.HttpRestR66ClientResponseHandler - org.waarp.openr66.protocol.http.rest.client.HttpRestR66ClientResponseHandler.channelRead0(HttpRestR66ClientResponseHandler.java:328) : Error: 400 Bad Request
```

Regards,

Alex

**Comment by bcarlin** [comment]
IMHO, it is not a bug. 

When I ty your commands (on version 3.0.7) I got:

~~~sh
bca@work ~/P/w/t/3.0.7 ➜  curl -sS -XPOST -d '{"@model":"DbRule",HOSTIDS:null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS": "<tasks></tasks>","UPDATEDINFO":0,"IDRULE":"test"}' '127.0.1.1:8088/rules'
{"X-method":"POST","path":"/rules","base":"rules","uri":{},"answer":{"@model":"DbRule","HOSTIDS":null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS":"<tasks></tasks>","UPDATEDINFO":3,"IDRULE":"test"},"command":"CREATE","message":"OK","code":200}⏎

bca@work ~/P/w/t/3.0.7 ➜ curl -sS -XPOST -d '{"@model":"DbRule",HOSTIDS:null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","UPDATEDINFO":0,"IDRULE":"test_2"}' '127.0.1.1:8088/rules'
{"X-method":"POST","path":"/rules","base":"rules","uri":{},"answer":{"@model":"DbRule","HOSTIDS":null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS":"<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","UPDATEDINFO":3,"IDRULE":"test_2"},"command":"CREATE","message":"OK","code":200}⏎

bca@work ~/P/w/t/3.0.7 ➜ curl -sS -XPOST -d '{"@model":"DbRule",HOSTIDS:null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS": "<tasks></tasks>","UPDATEDINFO":0,"IDRULE":"test"}' '127.0.1.1:8088/rules'
{"X-method":"POST","path":"/rules","base":"rules","uri":{},"message":"Bad Request","code":400,"detail":"Issue while inserting to database"}Will close session in DataModelRestMethodHandler

bca@work ~/P/w/t/3.0.7 ➜ curl -sS -XPOST -d '{"@model":"DbRule",HOSTIDS:null,"MODETRANS":2,"RECVPATH":"/recv","SENDPATH":"/send","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SPOSTTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS": "<tasks><task><type>LOG</type><path>log</path><delay>0</delay><comment></comment></task></tasks>","UPDATEDINFO":0,"IDRULE":"test_2"}' '127.0.1.1:8088/rules'
{"X-method":"POST","path":"/rules","base":"rules","uri":{},"message":"Bad Request","code":400,"detail":"Issue while inserting to database"}Will close session in DataModelRestMethodHandler
~~~

I run both curl command twice. For both, I have the same results: 
- It works the first time
- It fails the second time with the same error message as you ("code":400,"detail":"Issue while inserting to database")

Which is normal. As per the [REST documentation](http://waarp.github.io/Waarp/WaarpR66RestAPI.html):
- `POST /uri` means **create** one element according to body in Json format
- `PUT /uri/id` means **update** one element specified by the id (and for Transfers additionnal uri arguments or in body as Json format) using body in Json format for data

**Comment by alexbarta** [comment]
Indeed in the previous example I posted, curl did work (sorry about that)! Still having issues with this one:

```
curl -sS -XPOST -d'{"IDRULE":"TESTRECV","ARCHIVEPATH":"arch","RECVPATH":"in","SENDPATH":"root_out/TESTRECV”,  "WORKPATH" : "work", "HOSTIDS" : "<hostids><hostid>TEST</hostid></hostids>",        "MODETRANS" : 2, "RPOSTTASKS" : "<tasks><task><type>MOVERENAME</type><path>#INPATH#/#ORIGINALFILENAME#</path><delay>0</delay><comment></comment></task></tasks>",  "SPOSTTASKS" : "<tasks><task><type>MOVE</type><path>/waarp_data/root_out/TEST/TEST</path><delay>0</delay><comment></comment></task></tasks>", "RPRETASKS": "<tasks></tasks>", "RERRORTASKS": "<tasks></tasks>", "SPRETASKS": "<tasks></tasks>", "SERRORTASKS": "<tasks></tasks>"}' 'localhost:8088/rules'

{"X-method":"POST","path":"/rules","base":"rules","uri":{},"message":"Bad Request","code":400,"detail":"Issue while inserting into database"}
```
Curiously, throws a not enough argument exception (to me looks complete!)
```
12/02/2017/12:38:48.036 WARN [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-15] org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:438) : Error
org.waarp.gateway.kernel.exception.HttpIncorrectRequestException: Issue while inserting into database
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:105)
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:54)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.post(DataModelRestMethodHandler.java:355)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.endParsingRequest(DataModelRestMethodHandler.java:166)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.bodyChunk(HttpRestHandler.java:692)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:427)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:87)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.waarp.common.database.exception.WaarpDatabaseSqlException: Not enough argument to create the object
	at org.waarp.openr66.database.data.DbRule.<init>(DbRule.java:662)
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:103)
	... 32 common frames omitted
```

**Comment by bcarlin** [comment]
Maybe it is an error of copy /past and formatting, but the JSON in your curl command is not correct at char 92:

~~~
... "SENDPATH":"root_out/TESTRECV” ...
~~~

look after TESTRECV, the delimiter is `”` (unicode: right double quotation mark) and not `"` (unicode: quotation mark). setting the right quote mark in your command makes it work.

**Comment by alexbarta** [comment]
Actually the paste issue is due to mac notepad that replaces double quotes automatically.
