### ISSUE TITLE
Monitoring Rest API GETs on /server always return zero 

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#217]
Hi @fredericBregier , @bcarlin 

I'm trying to collect metrics from GET on /server resource. Even when some transfer is ongoing, almost all metrics are zero valued (except NetworkConnections, NbThreads, SecondsRunning, and several timestamps). Do you have some insight on this one? Actually I'm very confused..

Regards,

Alex

```
curl -sS localhost:8088/server | python -mjson.tool
{
    "X-method": "GET", 
    "answer": {
        "results": [
            {
                "Date": "2017-01-28T14:36:10.516Z", 
                "ERRORTYPES": {
                    "BadAuthent": 0, 
                    "Canceled": 0, 
                    "CommandNotFound": 0, 
                    "ConnectionImpossible": 0, 
                    "Disconnection": 0, 
                    "ExternalOp": 0, 
                    "FileNotFound": 0, 
                    "FinalOp": 0, 
                    "Internal": 0, 
                    "KnownHost": 0, 
                    "MD5Error": 0, 
                    "PassThroughMode": 0, 
                    "QueryAlreadyFinished": 0, 
                    "QueryStillRunning": 0, 
                    "RemoteError": 0, 
                    "RemoteShutdown": 0, 
                    "RemotelyUnknown": 0, 
                    "ServerOverloaded": 0, 
                    "Shutdown": 0, 
                    "Stopped": 0, 
                    "TransferError": 0, 
                    "Unimplemented": 0, 
                    "Unknown": 0, 
                    "Warning": 0
                }, 
                "FromDate": "2017-01-27T14:36:10.514Z", 
                "HostID": "serverwaarp", 
                "InBandwidth": 0, 
                "LastRun": "2017-01-28T14:36:10.514Z", 
                "NbThreads": 100, 
                "NetworkConnections": 3, 
                "OVERALL": {
                    "AllTransfer": 0, 
                    "Done": 0, 
                    "Error": 0, 
                    "InAll": 0, 
                    "InError": 0, 
                    "InRunning": 0, 
                    "Interrupted": 0, 
                    "LastInRunning": "2017-01-28T14:30:43.207Z", 
                    "LastOutRunning": "2017-01-28T01:18:23.124Z", 
                    "NotUpdated": 0, 
                    "OutAll": 0, 
                    "OutError": 0, 
                    "OutRunning": 0, 
                    "Running": 0, 
                    "ToSubmit": 0, 
                    "Unknown": 0
                }, 
                "OutBandwidth": 0, 
                "RUNNINGSTEPS": {
                    "AllRunning": 0, 
                    "CompleteOk": 0, 
                    "InitOk": 0, 
                    "PostProcessingOk": 0, 
                    "PreProcessingOk": 0, 
                    "Running": 0, 
                    "TransferOk": 0
                }, 
                "STEPS": {
                    "AllDone": 0, 
                    "Error": 0, 
                    "Notask": 0, 
                    "Posttask": 0, 
                    "Pretask": 0, 
                    "Transfer": 0
                }, 
                "SecondsRunning": 47867
            }
        ]
    }, 
    "base": "server", 
    "code": 200, 
    "command": "GetStatus", 
    "detail": "Current Waarp R66 status", 
    "message": "OK", 
    "path": "/server", 
    "uri": {}
}
```

**Comment by fredericBregier** [comment]
That's look like a bug ;-)
Thanks for reporting. We will investçigate.
@bcarlin ?

**Comment by bcarlin** [comment]
It seems indeed to be a bug...

**Comment by bcarlin** [comment]
I cannot reproduce it, and all data seem right on my end:

~~~http
bca@work ~/P/w/t/3.0.7 ➜ http GET 127.0.1.1:8088/server
HTTP/1.1 200 OK
connection: keep-alive
content-length: 1317
content-length: 1317
content-type: application/json
referer: /server

{
    "X-method": "GET",
    "answer": {
        "results": [
            {
                "Date": "2017-03-22T17:48:22.392+01:00",
                "ERRORTYPES": {
                    "BadAuthent": 0,
                    "Canceled": 0,
                    "CommandNotFound": 0,
                    "ConnectionImpossible": 0,
                    "Disconnection": 0,
                    "ExternalOp": 0,
                    "FileNotFound": 0,
                    "FinalOp": 0,
                    "Internal": 0,
                    "KnownHost": 0,
                    "MD5Error": 0,
                    "PassThroughMode": 0,
                    "QueryAlreadyFinished": 0,
                    "QueryStillRunning": 0,
                    "RemoteError": 0,
                    "RemoteShutdown": 0,
                    "RemotelyUnknown": 0,
                    "ServerOverloaded": 0,
                    "Shutdown": 1,
                    "Stopped": 0,
                    "TransferError": 0,
                    "Unimplemented": 0,
                    "Unknown": 0,
                    "Warning": 0
                },
                "FromDate": "2017-03-21T17:48:22.386+01:00",
                "HostID": "server1",
                "InBandwidth": 0,
                "LastRun": "2017-03-22T17:48:22.386+01:00",
                "NbThreads": 109,
                "NetworkConnections": 1,
                "OVERALL": {
                    "AllTransfer": 2,
                    "Done": 1,
                    "Error": 1,
                    "InAll": 2,
                    "InError": 1,
                    "InRunning": 0,
                    "Interrupted": 0,
                    "LastInRunning": "2017-03-22T17:46:02.069+01:00",
                    "LastOutRunning": "2017-03-22T17:44:58.473+01:00",
                    "NotUpdated": 0,
                    "OutAll": 2,
                    "OutError": 1,
                    "OutRunning": 0,
                    "Running": 0,
                    "ToSubmit": 0,
                    "Unknown": 0
                },
                "OutBandwidth": 0,
                "RUNNINGSTEPS": {
                    "AllRunning": 0,
                    "CompleteOk": 0,
                    "InitOk": 0,
                    "PostProcessingOk": 0,
                    "PreProcessingOk": 0,
                    "Running": 0,
                    "TransferOk": 0
                },
                "STEPS": {
                    "AllDone": 1,
                    "Error": 1,
                    "Notask": 0,
                    "Posttask": 0,
                    "Pretask": 0,
                    "Transfer": 0
                },
                "SecondsRunning": 203
            }
        ]
    },
    "base": "server",
    "code": 200,
    "command": "GetStatus",
    "detail": "Current Waarp R66 status",
    "message": "OK",
    "path": "/server",
    "uri": {}
}
~~~

I do not know what could have gone wrong for you... anything unusual in the logs ?

**Comment by alexbarta** [comment]
In the logs here is the exception that  appears multiple times when /server is invoked.

```
15/02/2017/12:57:26.972 ERROR [org.waarp.openr66.database.data.DbTaskRunner] [HttpWorker-18] org.waarp.openr66.database.data.DbTaskRunner.finishSelectOrCountPrepareStatement(DbTaskRunner.java:2143) : Database SQL Error: Cannot set timestamp
java.sql.SQLException: No operations allowed after statement closed.
       	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
       	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
       	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
       	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
       	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:436)
       	at com.mysql.jdbc.PreparedStatement.setTimestamp(PreparedStatement.java:4182)
       	at com.mysql.jdbc.jdbc2.optional.PreparedStatementWrapper.setTimestamp(PreparedStatementWrapper.java:429)
       	at org.waarp.openr66.database.data.DbTaskRunner.finishSelectOrCountPrepareStatement(DbTaskRunner.java:2141)
       	at org.waarp.openr66.protocol.localhandler.Monitoring.run(Monitoring.java:436)
       	at org.waarp.openr66.protocol.http.rest.handler.HttpRestServerR66Handler.endParsingRequest(HttpRestServerR66Handler.java:85)
       	at org.waarp.gateway.kernel.rest.HttpRestHandler.bodyChunk(HttpRestHandler.java:692)
       	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:427)
       	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:87)
       	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
       	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
       	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
       	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
       	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
       	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
       	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
       	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
       	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
       	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
       	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
       	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
       	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
       	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
       	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bcarlin** [comment]
Seeing the stacktrace, I thought maybe the issue was specific to MySQL, but I cannot reproduce it either...

A little more context about what happened before that error would help point in the right direction (the full logs for example...)

**Comment by bcarlin** [comment]
I think it might be a side-effect of #223 ...

**Comment by bcarlin** [comment]
the work now continues in #234 (this ticket regroups all problems about database connections...)
