### ISSUE TITLE
r66multisyncsend fails when subfolder is present

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#219]
Hi @fredericBregier , @bcarlin 

It seems I have found another bug. This time I'm running a multireceive transfer using filename regex '*' . Currently my out folder structure on the server is the following:
```
tree out/
out/
├── test1.txt
└── test_folder
    └── test2.txt
```
I have two files to receive, but one is contained in a subfolder (test2.txt in this case). When running the following command `r66multisyncsend -to serverwaarp-ssl -rule rule4 -file '*'` , first file text1.txt is processed correctly, but text2.txt fails with the following exception:
```
org.waarp.openr66.protocol.exception.OpenR66ProtocolBusinessRemoteFileNotFoundException: ErrorPacket:(3:f) PreTask in error: File cannot be read: /opt/R66/data/out/test2.txt
	at org.waarp.openr66.protocol.localhandler.ConnectionActions.errorMesg(ConnectionActions.java:631)
	at org.waarp.openr66.protocol.localhandler.LocalServerHandler.channelRead0(LocalServerHandler.java:188)
	at org.waarp.openr66.protocol.localhandler.LocalServerHandler.channelRead0(LocalServerHandler.java:86)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:440)
	at io.netty.channel.local.LocalChannel.access$500(LocalChannel.java:47)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:396)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

```
It seems that Waarp ignores the subfolder, looking for the file in a wrong path eventually. What do you think about this?

Best

Alex

**Comment by fredericBregier** [comment]
Probably yes, this is a bug in the sens it does not support initially subdirectories. We might consider to extend this to support recusrivity.
@bcarlin WDYT ?

**Comment by bcarlin** [comment]
IMO, if it was not designed to support subdirectories, then it should either:

- completely ignore test2.txt
- fail on trying to send test_folder

(mabe even both!)

It short term, I think we should just ignore directories.

In the long term, the ideal for me would be to keep the same semantics as other tools that copy files (cp, scp, etc...):

- The same command should be used to send one or more files: `r66send -file orig1,orig2`
- Subfolders recursivity should be explicit
- jokers should be consistent: `?` for a character, `*` for a path segment (delimited by path separators -- `/` or `\` depending on the OS) and `**` for subpaths
- if a match is a directory, it is ignored (we cannot send a directory!)
  
For example, with the following subtree 

```
tree out/
out/
├── test1.txt
├── test2.txt
└── subfolder
    ├── test3.txt
    └── test4.txt
```

we would have the following matches:

Pattern | match
------------ | -------------
test1.txt,test2.txt | test1.txt and test2.txt
`test?.txt` | test1.txt and test2.txt
`test?` | nothing
`test?.*` | test1.txt and test2.txt
`*` | test1.txt and test2.txt
`**` | nothing
`**/*` | test3.txt and test4.txt
`**/*4.txt` | test4.txt
`**/test?.txt` | test3.txt and test4.txt
`*,**/*` | test1.txt, test2.txt, test3.txt and test4.txt

What de you all think ?

**Comment by alexbarta** [comment]
I agree, in the short term subfolders should be ignored without failing.. maybe a command line that allows subfolder to be considered.
