### ISSUE TITLE
Having troubles posting rule task

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#220]
Hi @fredericBregier , @bcarlin 

Currently I have some trouble creating a new rule (server return 400), here below my post body:
```
{
  "WORKPATH": "/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/ongoing",
  "SPOSTTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVE</type><path>#OUTPATH#/sent</path></task></tasks>",
  "ARCHIVEPATH": "/arch",
  "MODETRANS": 1,
  "RECVPATH": "/root_in/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onmove",
  "IDRULE": "LUNA__ACEAFATTURE.OUTBOUND.SEND",
  "RPOSTTASKS": "<tasks><task><type>MOVERENAME</type><path>/waarp_data/root_out/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.RECV/ready/#ORIGINALFILENAME#</path><delay>0</delay><comment></comment></task></tasks>",
  "HOSTIDS": "<hostids><hostid>LUNA-1</hostid></hostids>",
  "RERRORTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVERENAME</type><path>/waarp_data/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onerror</path></task></tasks>",
  "SENDPATH": "/out/ready"
}
```
The log:
```
23/02/2017/15:54:44.288 DEBUG [org.waarp.gateway.kernel.rest.RestArgument] [HttpWorker-50] org.waarp.gateway.kernel.rest.RestArgument.setFromArgument(RestArgument.java:338) : DEBUG: {"X-method":"POST","path":"/rules","base":"rules","uri":{}}
 {"hasBody":false,"X-method":"POST","path":"/rules","base":"rules","uri":{},"header":{"User-Agent":"curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2","Host":"localhost:8086","Accept":"*/*","Content-Length":"862","Content-Type":"application/x-www-form-urlencoded"},"X-Auth-Role":127}
23/02/2017/15:54:44.289 DEBUG [org.waarp.openr66.database.data.DbRule] [HttpWorker-50] org.waarp.openr66.database.data.DbRule.setTasksRule(DbRule.java:1003) : RuleTask: <tasks></tasks>
23/02/2017/15:54:44.290 DEBUG [org.waarp.openr66.database.data.DbRule] [HttpWorker-50] org.waarp.openr66.database.data.DbRule.setTasksRule(DbRule.java:1003) : RuleTask: <tasks></tasks>
23/02/2017/15:54:44.290 DEBUG [org.waarp.openr66.database.data.DbRule] [HttpWorker-50] org.waarp.openr66.database.data.DbRule.setTasksRule(DbRule.java:1003) : RuleTask: <tasks></tasks>
23/02/2017/15:54:44.291 DEBUG [org.waarp.openr66.database.data.DbRule] [HttpWorker-50] org.waarp.openr66.database.data.DbRule.setTasksRule(DbRule.java:1003) : RuleTask: <tasks></tasks>
23/02/2017/15:54:44.292 DEBUG [org.waarp.openr66.database.data.DbRule] [HttpWorker-50] org.waarp.openr66.database.data.DbRule.setTasksRule(DbRule.java:1003) : RuleTask: <tasks></tasks>
23/02/2017/15:54:44.292 DEBUG [org.waarp.openr66.database.data.DbRule] [HttpWorker-50] org.waarp.openr66.database.data.DbRule.setTasksRule(DbRule.java:1003) : RuleTask: <tasks></tasks>
23/02/2017/15:54:44.294 WARN [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-50] org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:438) : Error
org.waarp.gateway.kernel.exception.HttpIncorrectRequestException: Issue while inserting into database
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:105)
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:54)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.post(DataModelRestMethodHandler.java:355)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.endParsingRequest(DataModelRestMethodHandler.java:166)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.bodyChunk(HttpRestHandler.java:692)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:427)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:87)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.waarp.common.database.exception.WaarpDatabaseSqlException: Not enough argument to create the object
	at org.waarp.openr66.database.data.DbRule.<init>(DbRule.java:662)
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:103)
	... 32 common frames omitted

```

When I remove RERRORTASKS , post ends up correctly 200. When I insert manually the task in the web gui I get no error, so it seems is a REST problem.. 

Regards

Alex

**Comment by alexbarta** [comment]
Sorry I meant **RPOSTTASKS** field is causing trouble.

**Comment by bcarlin** [comment]
The query seems incorrect.

When I try the query with your data, I got no error:

~~~sh
bca@work ~/P/w/t/3.0.7 ➜ curl -sS -XPOST -d '{"WORKPATH":"/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/ongoing","SPOSTTASKS":"<tasks><task><delay>0</delay><comment></comment><type>MOVE</type><path>#OUTPATH#/sent</path></task></tasks>","ARCHIVEPATH":"/arch","MODETRANS":1,"RECVPATH":"/root_in/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onmove","IDRULE":"LUNA__ACEAFATTURE.OUTBOUND.SEND","RPOSTTASKS":"<tasks><task><type>MOVERENAME</type><path>/waarp_data/root_out/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.RECV/ready/#ORIGINALFILENAME#</path><delay>0</delay><comment></comment></task></tasks>","HOSTIDS":"<hostids><hostid>LUNA-1</hostid></hostids>","RERRORTASKS":"<tasks><task><delay>0</delay><comment></comment><type>MOVERENAME</type><path>/waarp_data/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onerror</path></task></tasks>","SENDPATH":"/out/ready"}' '127.0.1.1:8088/rules'
{"X-method":"POST","path":"/rules","base":"rules","uri":{},"answer":{"@model":"DbRule","HOSTIDS":"<hostids><hostid>LUNA-1</hostid></hostids>","MODETRANS":1,"RECVPATH":"/root_in/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onmove","SENDPATH":"/out/ready","ARCHIVEPATH":"/arch","WORKPATH":"/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/ongoing","RPRETASKS":"<tasks></tasks>","RPOSTTASKS":"<tasks><task><type>MOVERENAME</type><path>/waarp_data/root_out/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.RECV/ready/#ORIGINALFILENAME#</path><delay>0</delay><comment></comment></task></tasks>","RERRORTASKS":"<tasks><task><type>MOVERENAME</type><path>/waarp_data/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onerror</path><delay>0</delay><comment></comment></task></tasks>","SPRETASKS":"<tasks></tasks>","SPOSTTASKS":"<tasks><task><type>MOVE</type><path>#OUTPATH#/sent</path><delay>0</delay><comment></comment></task></tasks>","SERRORTASKS":"<tasks></tasks>","UPDATEDINFO":3,"IDRULE":"LUNA__ACEAFATTURE.OUTBOUND.SEND"},"command":"CREATE","message":"OK","code":200}
~~~

To reproduce your error (I got exactly the same stacktrace in the logs), I had to run a curl request without body:

~~~sh
bca@work ~/P/w/t/3.0.7 ➜ curl -sS -XPOST '127.0.1.1:8088/rules'
{"X-method":"POST","path":"/rules","base":"rules","uri":{},"message":"Bad Request","code":400,"detail":"Issue while inserting into database"}
~~~

I am hinted by the first line of your log:

~~~json
{"hasBody":false,"X-method":"POST","path":"/rules","base":"rules","uri":{},"header":{"User-Agent":"curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2","Host":"localhost:8086","Accept":"*/*","Content-Length":"862","Content-Type":"application/x-www-form-urlencoded"},"X-Auth-Role":127}
~~~

The query seems to have no body.

**Comment by alexbarta** [comment]
I think it's same issue posted on #215 . 

similar  example going wrong on my side:

```
curl -sS -d '{"WORKPATH": "/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/ongoing", "SPOSTTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVE</type><path>#OUTPATH#/sent</path></task></tasks>", "ARCHIVEPATH": "/arch", "MODETRANS": 1, "RECVPATH": "/root_in/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onmove", "IDRULE": "LUNA__ACEAFATTURE.OUTBOUND.SEND", "RPOSTTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVERENAME</type><path>/waarp_data/root_out/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.RECV/ready/#ORIGINALFILENAME#</path></task><task><delay>0</delay><comment></comment><type>EXEC</type><path>/bin/logger WAARP_INFO #REQUESTEDHOST# RECV FILE #ORIGINALFILENAME# FROM #REQUESTERHOST#, RULE: #RULE#, CURRENT_FILEPATH: #TRUEFULLPATH#</path></task></tasks>", "HOSTIDS": "<hostids><hostid>LUNA-1</hostid></hostids>", "RERRORTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVE</type><path>/waarp_data/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onerror</path></task><task><delay>0</delay><comment></comment><type>EXEC</type><path>/bin/logger WAARP_CRIT #REQUESTEDHOST# RECV FILE #ORIGINALFILENAME# FROM #REQUESTERHOST#, RULE: #RULE#, CURRENT_FILEPATH: #TRUEFULLPATH#, ERROR: #ERRORMSG#</path></task></tasks>", "SENDPATH":"/out"}' 127.0.0.1:8088/rules

{"X-method":"POST","path":"/rules","base":"rules","uri":{},"message":"Bad Request","code":400,"detail":"Issue while inserting into database"}
```

I have also tcpdumped the rest invocation
```
..R.)../POST /rules HTTP/1.1
User-Agent: curl/7.30.0
Host: 127.0.0.1:8088
Accept: */*
Content-Length: 1285
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue


12:58:46.379847 IP 192.168.0.1.50782 > 192.168.0.16.radan-http: Flags [P.], seq 177:1462, ack 1, win 8235, options [nop,nop,TS val 3364707087 ecr 700829232], length 1285
D.'... +[S...........^.....
..[.)..0{"WORKPATH": "/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/ongoing", "SPOSTTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVE</type><path>#OUTPATH#/sent</path></task></tasks>", "ARCHIVEPATH": "/arch", "MODETRANS": 1, "RECVPATH": "/root_in/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onmove", "IDRULE": "LUNA__ACEAFATTURE.OUTBOUND.SEND", "RPOSTTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVERENAME</type><path>/waarp_data/root_out/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.RECV/ready/#ORIGINALFILENAME#</path></task><task><delay>0</delay><comment></comment><type>EXEC</type><path>/bin/logger WAARP_INFO #REQUESTEDHOST# RECV FILE #ORIGINALFILENAME# FROM #REQUESTERHOST#, RULE: #RULE#, CURRENT_FILEPATH: #TRUEFULLPATH#</path></task></tasks>", "HOSTIDS": "<hostids><hostid>LUNA-1</hostid></hostids>", "RERRORTASKS": "<tasks><task><delay>0</delay><comment></comment><type>MOVE</type><path>/waarp_data/root_work/data/outbound/LUNA__ACEAFATTURE.OUTBOUND.SEND/onerror</path></task><task><delay>0</delay><comment></comment><type>EXEC</type><path>/bin/logger WAARP_CRIT #REQUESTEDHOST# RECV FILE #ORIGINALFILENAME# FROM #REQUESTERHOST#, RULE: #RULE#, CURRENT_FILEPATH: #TRUEFULLPATH#, ERROR: #ERRORMSG#</path></task></tasks>", "SENDPATH":"/out"}
```

But still same exception

```
17/03/2017/12:58:46.382 WARN [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-8] org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:438) : Error
org.waarp.gateway.kernel.exception.HttpIncorrectRequestException: Issue while inserting into database
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:105)
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:54)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.post(DataModelRestMethodHandler.java:355)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.endParsingRequest(DataModelRestMethodHandler.java:166)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.bodyChunk(HttpRestHandler.java:692)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:427)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:87)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.waarp.common.database.exception.WaarpDatabaseSqlException: Not enough argument to create the object
	at org.waarp.openr66.database.data.DbRule.<init>(DbRule.java:662)
	at org.waarp.openr66.protocol.http.rest.handler.DbRuleR66RestMethodHandler.createItem(DbRuleR66RestMethodHandler.java:103)
	... 32 common frames omitted

```

**Comment by bcarlin** [comment]
Ok... I've nailed it:
if there are no errors in the body (like in #215), there is a bug that affects REST queries whose body is long enough to be splitted in several TCP packets. 
In my tests the above curl command generates 3 packets : one with the headers  and two with body data (the first having 944 bytes of data).
In this case, only the last body part is kept, which causes a JSON decoding error, which is turned into a 400 Bad Request because of the empty body. 

the same bug affected requests with the `Expects: 100-continue` that curl can add to queries, turning them into multi-TCP-Packets HTTP  requests, thus causing the bug.

I'm pushing a patch tomorrow...

**Comment by alexbarta** [comment]
great news! thanks a lot

Alex
