### ISSUE TITLE
Issue updating task via REST

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#221]
Hi @fredericBregier , @bcarlin 

I'm trying to update rule task via REST PUT request:
```
{
  "WORKPATH": "/work",
  "ARCHIVEPATH": "/arch",
  "SERRORTASKS": "<tasks><task><delay>0</delay><comment></comment><type>EXEC</type><path>/bin/logger WAARP_CRIT Error in sending #REQUESTERHOST# SEND TO #REQUESTEDHOST#  FILE #ORIGINALFULLPATH#/#ORIGINALFILENAME#</path></task></tasks>",
  "RECVPATH": "/in",
  "IDRULE": "RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A",
  "SENDPATH": "/out"
}

```
However it fails with 500 Internal Server error Code and the following exception appears server side:
```
08/02/2017/02:04:09.929 WARN [org.waarp.gateway.kernel.rest.HttpRestHandler] [HttpWorker-29] org.waarp.gateway.kernel.rest.HttpRestHandler.exceptionCaught(HttpRestHandler.java:749) : Exception com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
	at org.waarp.common.json.JsonHandler.getFromString(JsonHandler.java:83)
	at org.waarp.gateway.kernel.rest.DataModelRestMethodHandler.getBody(DataModelRestMethodHandler.java:135)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.getBodyJsonArgs(HttpRestHandler.java:721)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.bodyChunk(HttpRestHandler.java:688)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:427)
	at org.waarp.gateway.kernel.rest.HttpRestHandler.channelRead0(HttpRestHandler.java:87)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

Regards

Alex

**Comment by bcarlin** [comment]
Could you please provide the command or a code extract of how you run the query

**Comment by alexbarta** [comment]
Sincerely I'm not able to reproduce that issue myself. My best guess, as I directly seen via tcpdump, sometimes body arrives truncated (network issue? python client issue?) and that may provoke the exception above. I tried myself to send an incomplete body on purpose, but suprisingly I get 200 OK 

(see "SENDP truncated body element at the end)

```
curl -XPUT -sS -d '{"WORKPATH":"/work","ARCHIVEPATH":"/arch","SERRORTASKS":"<tasks><task><delay>0</delay><comment></comment><type>EXEC</type><path>/bin/logger WAARP_CRIT Error in sending #REQUESTERHOST# SEND TO #REQUESTEDHOST#  FILE #ORIGINALFULLPATH#/#ORIGINALFILENAME#</path></task></tasks","RECVPATH":"/in","IDRULE":"RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A","SENDP' 127.0.0.1:8088/rules/RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A


{"X-method":"PUT","path":"/rules/RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A","base":"rules","subpath":["RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A"],"uri":{"_id":"RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A"},"answer":{"@model":"DbRule","HOSTIDS":null,"MODETRANS":1,"RECVPATH":"/in","SENDPATH":"/out","ARCHIVEPATH":"/arch","WORKPATH":"/work","RPRETASKS":"<tasks></tasks>","RPOSTTASKS":"<tasks></tasks>","RERRORTASKS":"<tasks></tasks>","SPRETASKS":"<tasks></tasks>","SPOSTTASKS":"<tasks></tasks>","SERRORTASKS":"<tasks><task><type>EXEC</type><path>/bin/logger WAARP_CRIT Error in sending #REQUESTERHOST# SEND TO #REQUESTEDHOST#  FILE #ORIGINALFULLPATH#/#ORIGINALFILENAME#</path><delay>0</delay><comment></comment></task></tasks>","UPDATEDINFO":3,"IDRULE":"RECV_CLIENTWAARP-1_FROM_CLIENTWAARP-2_FLUSSO_A2A"},"command":"UPDATE","message":"OK","code":200}
```

**Comment by bcarlin** [comment]
For the first part, it was probably linked to #220.

Im' looking your last message. It indeed should fail because the body is not valid json...
