### ISSUE TITLE
Memory leak on Waarp Proxy service

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#251]
Hi @bcarlin 

today proxy service dumped following warn log. File transfer was not available having proxy service in this state.

Any hints?

Regards
```
2017-08-01 14:28:13.480 WARN [io.netty.channel.AbstractChannelHandlerContext] [Handler-3] An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3808428032, max: 3817865216)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:709)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:698)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:131)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:73)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by bcarlin** [comment]
Hi @alexbarta 

What makes you say it is a memory leak ?
From my experience, this is more of a system error that happens :
* when the -Xmx option of the java command that started the process is bigger than the available memory on the server (then you can decrease it)
* when the -Xmx option of the java command that started the process is lower that the amount of memory the process must use (then you should increase it)
* when there is really no more unused RAM on the system (then you should free some or add some)

Would you, by any chance, be in one of those cases ?

**Comment by alexbarta** [comment]
Hi Bruno,

We currently have for 8GB available and -Xmx option  is set to 4096 now. This kind of issue, happens on week/week and a half basis (same data transfer rate though). On service reboot allocates 2GB to start off, and then memory grows over week, provoking the out memory error described above. 
I could be wrong but sounds like netty or something else is leaking memory..  (On internet there is plenty of similar errors..)

Regards

**Comment by bcarlin** [comment]
It does indeed sounds like a memory leek...
We are looking into it
