### ISSUE TITLE
Waarp Proxy spawning lots of connection towards backend server

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#253]
Hi @bcarlin 

I have noticed that there are more than 400 hundred connections spawned by the proxy itself towards the backend proxy and then the waarp server. All these connections use ephemeral ports that are never released. Do you have any idea of what may cause this?

Regards

Alex.

```
...
tcp        0      0 192.168.2.42:54558          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54965          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54895          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54432          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54672          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54493          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54963          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54651          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54956          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54992          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54600          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:55005          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54844          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54697          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54371          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54658          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54729          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:55037          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54928          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54547          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54706          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54973          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54848          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54695          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54707          192.168.1.23:6667           ESTABLISHED 13443/java
tcp        0      0 192.168.2.42:54927          192.168.1.23:6667           ESTABLISHED 13443/java
...
```

**Comment by alexbarta** [comment]
I think I've found the cause of the persistent socket. It seems that SSL handshake error triggers the issue.

However I don't know how to reproduce such error. Any hints?
 
Regards,

Please see the log
```
2017-11-07 15:32:46.212 ERROR [org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory] [Handler-1] org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory.getExceptionFromTrappedException(OpenR66ExceptionTrappedFactory.java:173) : Unexpected exception from Outband Ref Channel: [id: 0x1d1cb437, L:/192.168.2.42:26667 ! R:/5.170.130.172:45436]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        ... 15 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1909)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:230)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1123)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1008)
        ... 17 common frames omitted
Caused by: sun.security.validator.ValidatorException: Certificate signature validation failed
        at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:212)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:227)
        at sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:99)
        at org.waarp.common.crypto.ssl.WaarpX509TrustManager.checkClientTrusted(WaarpX509TrustManager.java:79)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkClientTrusted(SSLContextImpl.java:929)
        at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1896)
        ... 25 common frames omitted
Caused by: java.security.SignatureException: Signature does not match.
        at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449)
        at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:392)
        at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:210)
        ... 32 common frames omitted
```

**Comment by marakiis** [comment]
I'm looking into this error.  
As it seems certain exceptions causes the server to abandon the transactions without closing the session.  
I will give more details as I found them.
